services:
  # Ambiente para testar a Versão 2.0 (Moderno)
  test-modern:
    build:
      context: .
      dockerfile: .docker/php82.dockerfile
    volumes:
      - .:/var/www
    container_name: upload-manager-php82
    command: php -v